site_name: Water Pollution USV Open Challenge
theme: bootstrap4
nav:
  - Home: index.md
  - 'Phase 1': 
    - About: 'phase1/index.md'
    - 'Evaluation Criteria': 'phase1/evaluation-criteria.md'
  - 'Phase 2':
    - About:  'phase2/index.md'
    - 'Evaluation Criteria': 'phase2/evaluation-criteria.md'
  - 'Nomenclature': 'nomenclature.md'
plugins:
  - bootstrap4-blockquotes
  - bootstrap4-tables
extra_css:
  - style.css
